### ISSUE TITLE
Visualize connections between local networks 

### ISSUE THREAD

**Issue by pmackay** [folklabs/connecting-communities#11]
@GreenCChampion, @GilesGibson can you think of ways in which items in your list/map of networks are connected? e.g.
- are local forums connected to neighbouring ones?
- where are the strong connections to the council?
- are there any collections of networks that regularly overlap?

**Comment by GreenCChampion** [comment]
- all local neighbourhood forums are part of a network - Lambeth Forum network (LFN)
- LFN does have a strong connection to the council. Otherwise in some cases there are strong links. -GPs would be well networked with their commissioners but not necessarily networked in their neighbourhood
- Generally health networks to do not regularly overlap with other networks eg education or local neighbourhood forums and I think this is something we want to change.

**Comment by pmackay** [comment]
@GreenCChampion I've added a column to your Map the Mappers sheet called "User need". Would be very interesting if you could add 1 sentence to each listing why that network/email list/etc needs to exist? Things like the forum networks are relatively obvious for Chris and me, but its much harder to understand why the email lists are maintained.

**Comment by pmackay** [comment]
@GilesGibson @GreenCChampion some questions:
- What's the difference between an Action group and a Forum? 
- Do "champions" networks collaborate?

I've had a quick go at dropping the mappers list into Kumu (which builds an actual map :) )

https://kumu.io/pmackay/lambeth#lambeth-community

Have tagged some of the elements. Might be useful for quick visualisations of where connections are happening and where they could be developed.
